version: "3.9"
services:
  masek-service:
    container_name: "masek-service"
    image: "masek-service"
    ports:
      - "${SERVICE_EXPOSED_PORT}:8080"
    environment:
      SPRING_RABBITMQ_ADDRESSES: ${RABBIT_ADDRESS}
      SERVICE_NAME: ${SERVICE_NAME}
      SERVICE_EXPOSED_PORT: ${SERVICE_EXPOSED_PORT}
      RABBITMQ_FANOUT_NAME: ${RABBITMQ_FANOUT_NAME}
      RABBITMQ_QUEUE_NAME: ${RABBITMQ_QUEUE_NAME}